"""BGA research modeling: examples, ontology measures, and domain encoders."""

from board_game_analysis.modeling.artifacts import (
    EXAMPLES_LOGICAL_KEY,
    MEASUREMENTS_LOGICAL_KEY,
    examples_payload_bytes,
    labels_for_observations,
    measurements_payload_bytes,
    observation_label_table,
    scalar_measurement_table,
    store_examples,
    store_measurements,
)
from board_game_analysis.modeling.encoders import (
    BAG_HASH_FAMILY,
    DEFAULT_DIM,
    ObservationBagEmbedder,
    StateBagEmbedder,
)
from board_game_analysis.modeling.examples import (
    ExampleBundle,
    ObservationExample,
    PairExample,
    SequenceExample,
    StateExample,
    examples_from_situation,
    examples_from_situations,
)
from board_game_analysis.modeling.measures import (
    MEASURE_METHOD,
    MEASURE_VERSION,
    SUPPORTED_METRIC_IDS,
    MeasureSpec,
    PairAsymmetry,
    default_measure_spec,
    measure_situation,
    measure_situations,
    pairwise_information_asymmetry,
)
from board_game_analysis.modeling.perspectives import (
    BGA_PERSPECTIVE_SPEC,
    PERSPECTIVE_DISTANCES_LOGICAL_KEY,
    PERSPECTIVES_LOGICAL_KEY,
    aligned_distance_pairs,
    mean_pair_distance,
    perspective_distances,
    perspective_table_from_observations,
    store_perspective_distances,
    store_perspectives,
)
from board_game_analysis.modeling.probes import RidgeRegressor, probe_column
from board_game_analysis.modeling.run_encode import (
    OBS_MODEL_LOGICAL_KEY,
    OBS_REPR_LOGICAL_KEY,
    PROBE_EVAL_LOGICAL_KEY,
    STATE_MODEL_LOGICAL_KEY,
    STATE_REPR_LOGICAL_KEY,
    EncodingBundle,
    bag_encoding_spec,
    encode_observations,
    encode_states,
    store_probe_evaluation,
)
from board_game_analysis.modeling.split import split_entities_by_game

__all__ = [
    "BAG_HASH_FAMILY",
    "BGA_PERSPECTIVE_SPEC",
    "DEFAULT_DIM",
    "EXAMPLES_LOGICAL_KEY",
    "MEASUREMENTS_LOGICAL_KEY",
    "MEASURE_METHOD",
    "MEASURE_VERSION",
    "OBS_MODEL_LOGICAL_KEY",
    "OBS_REPR_LOGICAL_KEY",
    "PERSPECTIVES_LOGICAL_KEY",
    "PERSPECTIVE_DISTANCES_LOGICAL_KEY",
    "PROBE_EVAL_LOGICAL_KEY",
    "STATE_MODEL_LOGICAL_KEY",
    "STATE_REPR_LOGICAL_KEY",
    "SUPPORTED_METRIC_IDS",
    "EncodingBundle",
    "ExampleBundle",
    "MeasureSpec",
    "ObservationBagEmbedder",
    "ObservationExample",
    "PairAsymmetry",
    "PairExample",
    "RidgeRegressor",
    "SequenceExample",
    "StateBagEmbedder",
    "StateExample",
    "aligned_distance_pairs",
    "bag_encoding_spec",
    "default_measure_spec",
    "encode_observations",
    "encode_states",
    "examples_from_situation",
    "examples_from_situations",
    "examples_payload_bytes",
    "labels_for_observations",
    "mean_pair_distance",
    "measure_situation",
    "measure_situations",
    "measurements_payload_bytes",
    "observation_label_table",
    "pairwise_information_asymmetry",
    "perspective_distances",
    "perspective_table_from_observations",
    "probe_column",
    "scalar_measurement_table",
    "split_entities_by_game",
    "store_examples",
    "store_measurements",
    "store_perspective_distances",
    "store_perspectives",
    "store_probe_evaluation",
]
